[package]
name = "mooshroom-core"
version = "0.1.0"
edition = "2021"
description = "mc"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
paste = "1.0.9"
thiserror = "1.0.37"
